/** @file
 *
 * Unicode mangling library, automatically generated
 *
 * to regenerate, use unicode/genunicodedata.py
 * Why this hader file? Because I couldn't find any working uppercase/lowercase
 * unicode builtin
 *
 * @warning Do not edit this file ny hand!
 * @author Bodom
 */

#pragma once


namespace Pol {
namespace Clib {

/**
 * Collection of static methods handling the very internals of Unicode Handling
 */
class UnicodeData
{
public:

  /**
   * Converts a char from uppercase to lowercase
   *
   * @warning Do not edit, this has been automatically generated
   */
  static char32_t toLower( char32_t chr )
  {
    switch( chr ) {
    TOLOWER_CASES
    default:
      return chr;
    }
  }

  /**
   * Converts a char from lowercase to uppercase
   *
   * @warning Do not edit, this has been automatically generated
   */
  static char32_t toUpper( char32_t chr )
  {
    switch( chr ) {
    TOUPPER_CASES
    default:
      return chr;
    }
  }

};

}
}
