#!/bin/bash
#
# Build Official Release

export BUILD64POL=1
#export USE_MYSQL=1

export LIBCRYPT="crypto"
export POL_BUILDTAG="ubuntu"
export CXX_MORE_OPTS="-O3 -DUSE_SYSTEM_ZLIB -DHAVE_OPENSSL -DNDEBUG -D_REENTRANT -DPOL_BUILDTAG=\\\"ubuntu\\\""

#use 4.6
#CC="gcc -std=c++0x -gstabs+ " LINKER="g++ -std=c++0x -gstabs+ " make -f makefile.gcc dist

#use 4.8
#CC="gcc-4.8 -std=c++11 -gstabs+ " LINKER="g++-4.8 -std=c++11 -gstabs+" make -f makefile.gcc dist

#use clang
CC="clang -std=c++11" LINKER="clang -std=c++11" make -f makefile.gcc dist

