#!/bin/bash
chmod +x bootstrap.sh
chmod +x tools/build/v2/engine/build.sh

./bootstrap.sh --prefix=build

./bjam toolset=gcc link=static runtime-link=static address-model=32 variant=release --abbreviate-paths --stagedir=lib/x86 --build-dir=build/x86 stage
./bjam toolset=gcc link=shared runtime-link=shared address-model=32 variant=release --abbreviate-paths --stagedir=lib/x86 --build-dir=build/x86 stage
./bjam toolset=gcc link=static runtime-link=static address-model=32 variant=debug --abbreviate-paths --stagedir=lib/x86 --build-dir=build/x86 stage
./bjam toolset=gcc link=static runtime-link=shared address-model=32 variant=debug --abbreviate-paths --stagedir=lib/x86 --build-dir=build/x86 stage