#!/bin/bash
#
# Build Official 32bit Release

unset BUILD64POL
#export USE_MYSQL=1

export LIBCRYPT="crypto"
export POL_BUILDTAG="ubuntu"
export CXX_MORE_OPTS="-O3 -DUSE_SYSTEM_ZLIB -DHAVE_OPENSSL -DNDEBUG -D_REENTRANT -DPOL_BUILDTAG=\\\"ubuntu\\\""

make -f makefile.gcc dist

