#!/bin/bash

CC=gcc-3.0 LINKER=g++-3.0 LIBCRYPT="crypto" POL_BUILDTAG=debian CXX_MORE_OPTS="-DHAVE_OPENSSL -DNDEBUG -D_REENTRANT -DPOL_BUILDTAG=\\\"debian\\\"" make -f makefile.gcc $*

#until CC=gcc-3.0 LINKER=g++-3.0 LIBCRYPT="crypto" POL_BUILDTAG=debian CXX_MORE_OPTS="-DHAVE_OPENSSL -DNDEBUG -D_REENTRANT -DPOL_BUILDTAG=\\\"debian\\\"" make -f makefile.gcc $*
#do
#    echo Tryinh again
#    sleep 10
#done

