set (plib_sources  # sorted !
  CMakeSources.cmake 
  StdAfx.h
  clidata.h
  filemapserver.cpp 
  filemapserver.h
  fsa.h
  inmemorymapserver.cpp
  inmemorymapserver.h
  mapblock.h
  mapcell.h
  mapfunc.cpp 
  mapfunc.h
  mapserver.cpp 
  mapserver.h
  mapshape.h
  mapsolid.h
  maptile.h
  maptileserver.cpp 
  maptileserver.h
  mapwriter.cpp
  mapwriter.h
  mul/map.h
  mul/tiledata.h
  objtype.h
  pkg.cpp 
  pkg.h
  polcfg.cpp
  polcfg.h
  polfile.h
  polfile1.cpp
  polfile2.cpp
  poltype.h
  realmdescriptor.cpp
  realmdescriptor.h
  staticblock.h
  staticserver.cpp
  staticserver.h
  stlastar.h
  systemstate.cpp
  systemstate.h
  tiles.cpp
  tiles.h
  uconst.h
  udatfile.h
  uoexpansion.cpp
  uoexpansion.h
  clientfiles/uoclientfiles.h
  clientfiles/RawMap.h
  clientfiles/RawMap.cpp
  clientfiles/uoclientfiles.cpp
  clientfiles/tiledatacache.h
  clientfiles/tiledatacache.cpp
  clientfiles/staticscache.h
  clientfiles/staticscache.cpp
  clientfiles/rawmapaccess.cpp
  uoinstallfinder.cpp
  uoinstallfinder.h
  uopreader/uop.cpp
  uopreader/uop.h
  uopreader/uopfile.ksy
  uopreader/uophash.h
  ustruct.h
)
