set (plib_sources  # sorted !
  CMakeSources.cmake 
  StdAfx.h
  clidata.h
  filemapserver.cpp 
  filemapserver.h
  fsa.h
  inmemorymapserver.cpp
  inmemorymapserver.h
  mapblob.h
  mapblock.h
  mapcell.h
  mapfunc.cpp 
  mapfunc.h
  mapserver.cpp 
  mapserver.h
  mapshape.h
  mapsolid.h
  maptile.h
  maptileserver.cpp 
  maptileserver.h
  mapwriter.cpp
  mapwriter.h
  mul/tiledata.h
  pkg.cpp 
  pkg.h
  polfile.h
  polfile1.cpp
  polfile2.cpp
  poltype.h
  RawMap.cpp
  RawMap.h
  realmdescriptor.cpp 
  realmdescriptor.h
  staticblock.h
  staticserver.cpp
  staticserver.h
  stlastar.h
  systemstate.cpp
  systemstate.h
  tiles.cpp
  tiles.h
  uconst.h
  udatfile.h
  uoexpansion.h
  uofile.h
  uofilei.h
  uofile00.cpp
  uofile01.cpp
  uofile02.cpp
  uofile04.cpp 
  uofile05.cpp
  uofile06.cpp
  uofile07.cpp
  uofile08.cpp
  uoinstallfinder.cpp
  uoinstallfinder.h
  uopreader/uop.cpp
  uopreader/uop.h
  uopreader/uopfile.ksy
  uopreader/uophash.h
  ustruct.h
)
