set (plib_sources  # sorted !
  ../pol/uofile00.cpp       # TODO: move all uofile*.cpp into the plib folder
  ../pol/uofile01.cpp
  ../pol/uofile02.cpp
  ../pol/uofile06.cpp
  ../pol/uofile07.cpp
  ../pol/uofile08.cpp
  ../uotool/uofile04.cpp 
  ../uotool/uofile05.cpp
  StdAfx.h
  filemapserver.cpp 
  filemapserver.h
  fsa.h
  inmemorymapserver.cpp
  inmemorymapserver.h
  mapblob.h
  mapblock.h
  mapcell.h
  mapfunc.cpp 
  mapfunc.h
  mapserver.cpp 
  mapserver.h
  mapshape.h
  mapsolid.h
  maptile.h
  maptileserver.cpp 
  maptileserver.h
  mapwriter.cpp
  mapwriter.h
  pkg.cpp 
  pkg.h
  realmdescriptor.cpp 
  realmdescriptor.h
  staticblock.h
  staticserver.cpp
  staticserver.h
  stlastar.h
  systemstate.cpp
  systemstate.h
  uoexpansion.h
)
