0: goto11
1: pop param 'e'
2: pop param 'b'
3: pop param 'a'
4: local #2
5: local #1
6: +
7: local #0
8: +
9: return
10: leave block(3)
11: goto31
12: pop param 'd'
13: pop param 'c'
14: pop param 'b'
15: pop param 'a'
16: local #3
17: local #2
18: *
19: local #1
20: local #0
21: *
22: +
23: 12L
24: local #1
25: 2L
26: makelocal
27: jmp userfunc @1
28: -
29: return
30: leave block(4)
31: global(a)
32: #
33: global #0
34: 2L
35: 3.5LF
36: 6.7LF
37: 9L
38: makelocal
39: jmp userfunc @12
40: :=
41: #
42: global #0
43: Func(1,0): <unknown>
44: #
45: progend
