/*
History
=======


Notes
=======

*/

#ifndef REAGENTS_H
#define REAGENTS_H

enum UREAGENT {
	REAGENT_BAT_WING	=		0xF78,
	REAGENT_BLACKMOOR	=		0xF79,
	REAGENT_BLACK_PEARL	=		0xF7A,
	REAGENT_BLOOD_MOSS	=		0xF7B,
	REAGENT_BLOODSPAWN	=		0xF7C,
	REAGENT_VIAL_OF_BLOOD	=	0xF7D,
	REAGENT_BONE			=	0xF7E,
	REAGENT_BRIMSTONE	=		0xF7F,
	REAGENT_DAEMON_BONE	=		0xF80,
	REAGENT_FERTILE_DIRT	=	0xF81,
	REAGENT_DRAGONS_BLOOD	=	0xF82,
	REAGENT_EXECUTIONERS_CAP=	0xF83,
	REAGENT_GARLIC			=	0xF84,
	REAGENT_GINSENG			=	0xF85,
	REAGENT_MANDRAKE_ROOT	=	0xF86,
	REAGENT_EYE_OF_NEWT		=	0xF87,
	REAGENT_NIGHTSHADE		=	0xF88,
	REAGENT_OBSIDIAN		=	0xF89,
	REAGENT_PIG_IRON		=	0xF8A,
	REAGENT_PUMICE			=	0xF8B,
	REAGENT_SULFUROUS_ASH	=	0xF8C,
	REAGENT_SPIDERS_SILK	=	0xF8D,
	REAGENT_SERPENTS_SCALES	=	0xF8E,
	REAGENT_VOLCANIC_ASH	=	0xF8F,
	REAGENT_DEAD_WOOD		=	0xF90,
	REAGENT_WORMS_HEART		=	0xF91
};
#endif
