if(MSVC)
  set(CMAKE_CXX_FLAGS_DEBUG_INIT          "/MT /Zi /Ob0 /Od /RTC1")    #/MDd /Zi /Ob0 /Od /RTC1
  set(CMAKE_CXX_FLAGS_MINSIZEREL_INIT     "/MT /O1 /Ob1 /DNDEBUG")     #/MD /O1 /Ob1 /DNDEBUG
  set(CMAKE_CXX_FLAGS_RELEASE_INIT        "/MT /O2 /Ob2 /DNDEBUG")     #/MD /O2 /Ob2 /DNDEBUG
  set(CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT "/MT /Zi /O2 /Ob1 /DNDEBUG") #/MD /Zi /O2 /Ob1 /DNDEBUG

  set(CMAKE_EXE_LINKER_FLAGS_DEBUG "/debug") # /debug /INCREMENTAL
  set(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO "/debug") # /debug /INCREMENTAL
  set(CMAKE_MODULE_LINKER_FLAGS_DEBUG "/debug") # /debug /INCREMENTAL
  set(CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO "/debug") # /debug /INCREMENTAL
endif()