
translate={
    'Account': 'AccountObjImp',
    'Armor': 'UArmor',
    'Array': 'ObjArray',
    'BinaryFile': 'BBinaryfile',
    'Boat': 'UBoat',
    'Client': 'EClientRefObjImp',
    'Container': 'UContainer',
    'Corpse': 'UCorpse',
    'DataFileElement': 'DataElemRefObjImp',
    'Datafile': 'DataFileRefObjImp',
    'Dictionary': 'BDictionary',
    'Door': 'UDoor',
		'Error': 'BError',
		'FunctionObject': 'BFunctionRef',
    'Guild': 'EGuildRefObjImp',
    'House': 'UHouse',
    'Lockable': 'ULockable',
    'Multi': 'UMulti',
    'Package': 'PackageObjImp',
    'Packet': 'BPacket',
    'Party': 'EPartyRefObjImp',
    'Plank': 'UPlank',
    'Polcore': 'PolCore',
    'Script': 'ScriptExObjImp',
    'StorageArea': 'StorageAreaImp',
    'StorageAreas': 'StorageAreasImp',
    'Struct': 'BStruct',
    'Weapon': 'UWeapon',
		'XMLAttributes': 'BXmlAttribute',
		'XMLFile': 'BXMLfile',
		'XMLNode': 'BXmlNode',
    }
for k,v in list(translate.items()):
    translate[v]=k

