set (bscript_sources    # sorted !
  ../../lib/EscriptGrammar/EscriptLexer.cpp
  ../../lib/EscriptGrammar/EscriptLexer.h
  ../../lib/EscriptGrammar/EscriptParser.cpp
  ../../lib/EscriptGrammar/EscriptParser.h
  ../../lib/EscriptGrammar/EscriptParserBaseListener.cpp
  ../../lib/EscriptGrammar/EscriptParserBaseListener.h
  ../../lib/EscriptGrammar/EscriptParserListener.cpp
  ../../lib/EscriptGrammar/EscriptParserListener.h
  CMakeSources.cmake
  StdAfx.h
  StoredToken.cpp
  StoredToken.h
  berror.cpp 
  berror.h
  blong.cpp 
  bobject.h
  bstruct.cpp
  bstruct.h
  compctx.cpp 
  compctx.h
  compiler.cpp
  compiler.h
  compilercfg.cpp 
  compilercfg.h
  compmodl.h
  config.h
  contiter.h
  dbl.cpp 
  dict.cpp 
  dict.h
  eprog.cpp
  eprog.h
  eprog2.cpp
  eprog3.cpp
  eprog_read.cpp
  escript.h
  escript_config.cpp
  escriptv.cpp
  escriptv.h
  escrutil.cpp
  escrutil.h
  execmodl.cpp
  execmodl.h
  exectype.h
  executor.cpp
  executor.h
  executortype.h
  expression.cpp
  expression.h
  filefmt.h
  fmodule.cpp
  fmodule.h
  impstr.h
  modules.h
  object.cpp 
  object.h
  objmembers.h
  objmethods.h
  objstrm.cpp
  operator.h
  options.h
  parser.cpp
  parser.h
  str.cpp 
  symcont.cpp
  symcont.h
  tkn_strm.cpp 
  token.cpp
  token.h
  tokens.cpp
  tokens.h
  userfunc.cpp
  userfunc.h
  verbtbl.h
)

