name: Testing

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: "windows-latest"
            cxx-compiler: cl
            c-compiler: cl
            compiler-version: default
            build-type: Release
            nopch: 0

          - os: "ubuntu-latest"
            cxx-compiler: clang++
            c-compiler: clang
            compiler-version: 8
            build-type: RelWithDebInfo
            nopch: 0
          

    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: Cache curl
        uses: actions/cache@v1
        with:
          path: lib/curl-7.57.0
          key: ${{ runner.os }}-${{ matrix.config.cxx-compiler }}-${{ matrix.config.compiler-version }}-curl-7.57.0

      - name: Install Compiler and Dependencies
        if: matrix.config.os == 'ubuntu-latest'
        shell: pwsh
        run: |
          sudo apt-get update

          $compiler = "${{ matrix.config.cxx-compiler }}"
          $version = "${{ matrix.config.compiler-version }}"

          if ($version -ne 'default') {
            sudo apt-get install "$compiler-$version" -y
            echo "$compiler-$version --version"
          }
          sudo apt-get install mysql-client libmysqlclient-dev kwstyle -y
          
          $ninja_version = "1.9.0"
          $cmake_version = "3.16.2"
          $cmake_archive = "cmake-$cmake_version-Linux-x86_64"
          wget -q "https://github.com/ninja-build/ninja/releases/download/v$ninja_version/ninja-linux.zip"
          unzip -q ninja-linux.zip -d bin-build
          wget -q "https://github.com/Kitware/CMake/releases/download/v$cmake_version/$cmake_archive.tar.gz"
          tar -xf "$cmake_archive.tar.gz"
          
          chmod +x bin-build/ninja
          chmod +x "$cmake_archive/bin/cmake"
          echo "::add-path::$Env:GITHUB_WORKSPACE/bin-build"
          echo "::add-path::$Env:GITHUB_WORKSPACE/$cmake_archive/bin"
      
      - name: Set CXX and CC
        shell: pwsh
        run: |
          $cxx_compiler = '${{ matrix.config.cxx-compiler }}'
          $c_compiler = '${{ matrix.config.c-compiler }}'
          $version = '${{ matrix.config.compiler-version }}'

          if ($version -ne 'default') {
            $cxx_compiler = "$cxx_compiler-$version"
            $c_compiler = "$c_compiler-$version"
          }

          echo "::set-env name=CXX::$cxx_compiler"
          echo "::set-env name=CC::$c_compiler"

      - name: Config
        run: |
          cd bin-build
          cmake .. -G Ninja
      - name: Build
        run: |
          cd bin-build
          cmake --build . --config ${{ matrix.config.build-type }} -- -j 2
      - name: testing
        run: |
          cd testsuite/escript
          ../../bin/ecompile test.src
          ../../bin/runecl test.ecl
          #cd ../../bin
          #./pol


      - name: Test
        run: |
          cd bin-build
          ctest -j2 --output-on-failure -C ${{ matrix.config.build-type }}
